### PR TITLE
Added Clarifying diagram for enabling azure search

### PR DESCRIPTION
**Pull request by plooploops**
While the md file indicated that we should hook in the ChatWebApp and ChatAPI, it was not clear how they would connect to Azure Search.  This should help avoid some configuration issues and hopefully the picture will help too.

### CODE REVIEW

**Comment by joelhulen** [comment]
@plooploops Thanks for your contribution! There are merge conflicts that are preventing us from accepting your PR. Can you please get the latest changes to the repo, resolve the merge conflicts, and then resubmit your PR? If you can do that, I'll accept the PR right away. Thanks!

**Comment by plooploops** [comment]
@joelhulen I went ahead and merged in the changes.  Let me know if that works for you!

**Comment by joelhulen** [comment]
Perfect! Thanks, @plooploops :)

**Comment by plooploops** [comment]
@joelhulen Looks like the merge had one part that was still to be accepted.  I submitted a new pr for it.

**Pull request merged**
